### ISSUE TITLE
Update to version 14.0

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/web-installer#27] opened 2018-09-06 08:42 UTC
To be consistent with the actual, current release of NC 14 update the webinstaller accordingly!

Many Thanks!

Regards, hitam4450

**Comment by gratuxri** [comment] 2018-09-17 12:51
Duplicate of #28

**Comment by MorrisJobke** [comment] 2018-09-28 09:52
731110c

**Closed as completed by MorrisJobke** 2018-09-28 09:52 UTC
